# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10
  identifier = "about"

[[main]]
  name = "Objectives"
  pageRef = "about/objectives"
  weight = 10
  parent = "about"

[[main]]
  name = "Consortium"
  pageRef = "about/consortium"
  weight = 20
  parent = "about"

[[main]]
  name = "Workpackage Overview"
  pageRef = "/workpackages"
  weight = 100
  parent = "about"
  identifer = "workpackages"

[[main]]
  name = "WP1 - Network"
  pageRef = "workpackages/01_Framework_European_Network"
  weight = 110
  identifer = "WP1"
  parent = "about"

[[main]]
  name = "WP2 - Best Practice"
  pageRef = "workpackages/02_Best_Practices"
  weight = 120
  identifer = "WP2"
  parent = "about"

[[main]]
  name = "WP3 - Tools and Services"
  pageRef = "workpackages/03_Tools_and_Services"
  weight = 130
  identifer = "WP3"
  parent = "about"

[[main]]
  name = "WP4 - Pilots and Drivers"
  pageRef = "workpackages/04_Pilots_and_Drivers"
  weight = 140
  identifer = "WP4"
  parent = "about"

[[main]]
  name = "WP5 - Capacity and Recognition"
  pageRef = "workpackages/05_Capacity_and_Recognition"
  weight = 150
  identifer = "WP5"
  parent = "about"

[[main]]
  name = "WP6 - Project Management"
  pageRef = "workpackages/06_Project_Management"
  weight = 160
  identifer = "WP6"
  parent = "about"

[[main]]
  name = "RSQkit"
  weight = 10
  pageRef = "services/RSQkit"
  parent = "Services"

[[main]]
  name = "SMP"
  weight = 20
  pageRef = "services/SMP"
  parent = "Services"

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
